### ISSUE TITLE
Timestamp is required

### ISSUE THREAD

**Issue by dtivel** [onovotny/NuGetKeyVaultSignTool#122] opened 2022-12-23 14:38 UTC
Passing a `null` timestamp service URL will cause an exception [here](https://github.com/novotnyllc/NuGetKeyVaultSignTool/blob/946e5c863a12a65feceecce50840dc611d9d1da8/NuGetKeyVaultSignTool.Core/SignCommand.cs#L64).  Also, [KeyVaultSignatureProvider requires a timestamp provider.](https://github.com/novotnyllc/NuGetKeyVaultSignTool/blob/946e5c863a12a65feceecce50840dc611d9d1da8/NuGetKeyVaultSignTool.Core/KeyVaultSignatureProvider.cs#L28)

**Comment by clairernovotny** [comment] 2023-01-03 16:42
This is by design and won't be fixed. Timestamps are required....

**Closed as completed by clairernovotny** 2023-01-03 16:42 UTC
Labels: wontfix
